<template>
  <div class="td-tree td-tree--hover">
    <td-tree-node-plus
      v-for="(node, index) in copyData"
      :node="node"
      :key="bindingKeyGenerator(node)"
      v-model="copyData[index]"
      :lazy="lazy"
      :load="load"
      :levelPadding="levelPadding"
      :checkable="checkable"
    >
    </td-tree-node-plus>
  </div>
</template>

<script>
import TdTreeNodePlus from './TreeNodePlus.vue'
export default {
  name: `td-tree-plus`,
  components: {
    TdTreeNodePlus
  },
  props: {
    data: {
      type: Array,
      required: true
    },
    lazy: {
      type: Boolean,
      default: false
    },
    load: {
      type: Function
    },
    levelPadding: {
      type: Number,
      default: 16
    },
    checkable: {
      type: Boolean,
      default: false
    },
    disableFunction: {
      type: Function,
      default: function () {
        return false
      }
    },
    disableClass: {
      type: String,
      default: 'disabled-node'
    },
    bindingKeyGenerator: {
      type: Function,
      default: function (node) {
        return `${(node.__level || '')} ${Math.random()} ${node.title}`
      }
    },
    defaultPlaceholder: {
      type: String,
      default: ''
    },
    nodeInsertionIconManifest: {
      type: Object,
      default () {
        return {
          visible: true,
          icon: 'https://backstage-img-ssl.a.88cdn.com/019fc2a136a2881181e73fea74a4836efc02195d'
        }
      }
    },
    expandWhenDoubleClick: {
      type: Boolean,
      default: false
    }
  },
  provide () {
    return {
      root: this
    }
  },
  data () {
    return {
      copyData: [],
      // chooseNode 是一个TreeNode Instance
      chosenNode: null
    }
  },
  created () {
    try {
      this.copyData = JSON.parse(JSON.stringify(this.data))
    } catch (err) {
      this.copyData = []
    }
    for (let i = 0; i < this.data.length; i++) {
      this.autoGeneratedKey(this.copyData[i], null)
    }
  },
  methods: {
    handleChangeNode (node, index) {
      this.$set(this.copyData, index, node)
    },
    autoGeneratedKey (treeNode, parentNode) {
      treeNode.__level = parentNode ? parentNode.__level + 1 : 1
      let children = treeNode.children
      if (children && children.length) {
        for (let i = 0; i < children.length; i++) {
          this.autoGeneratedKey(children[i], treeNode)
        }
      }
    }
  },
  watch: {
    chosenNode (newVal) {
      this.$emit('changeChosenNode', newVal)
    }
  }
}
</script>
